CREATE TABLE STET_PAYMENT_CONSENT (
  REQUEST_RESOURCE_ID          VARCHAR(255)   NOT NULL,
  REQUEST_BODY                 CLOB           NOT NULL,
  X_REQUEST_ID                 VARCHAR(255) NOT NULL,
  REQUEST_INITIATION_TIMESTAMP TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  CONSENT_STATUS               VARCHAR(64)    DEFAULT 0,
  CLIENT_ID                    VARCHAR(255)   NOT NULL,
  PRIMARY KEY (REQUEST_RESOURCE_ID)
)
 /

CREATE TABLE STET_PAYMENT_INSTRUCTION (
  REQUEST_RESOURCE_ID        VARCHAR(255) NOT NULL,
  INSTRUCTION_END_TO_END_ID             VARCHAR(255) NOT NULL,
  INSTRUCTION_STATUS             VARCHAR(64)    DEFAULT 0,
  INSTRUCTION_BODY     CLOB           NOT NULL,
  PRIMARY KEY (REQUEST_RESOURCE_ID, INSTRUCTION_END_TO_END_ID),
  CONSTRAINT FK_REQUEST_RESOURCE_ID FOREIGN KEY
  (REQUEST_RESOURCE_ID) REFERENCES STET_PAYMENT_CONSENT (REQUEST_RESOURCE_ID)
    ON DELETE CASCADE
)
 /

CREATE TABLE STET_PAYMENT_USER_MAPPING (
  USER_ID                    VARCHAR(255) NOT NULL,
  REQUEST_RESOURCE_ID        VARCHAR(255) NOT NULL,
  DEBTOR_ACCOUNT             VARCHAR(255),
  UPDATED_TIMESTAMP          TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (USER_ID, REQUEST_RESOURCE_ID),
  CONSTRAINT FK_USER_MAPPING FOREIGN KEY
  (REQUEST_RESOURCE_ID) REFERENCES STET_PAYMENT_CONSENT (REQUEST_RESOURCE_ID)
    ON DELETE CASCADE
)
 /

CREATE TABLE STET_PYMNT_REVOCATION_HISTORY (
  REVOKED_BY           VARCHAR(255)  NOT NULL,
  REQUEST_RESOURCE_ID           VARCHAR(255)  NOT NULL,
  INSTRUCTION_END_TO_END_ID             VARCHAR(255) DEFAULT 'ALL',
  REASON               VARCHAR(1000) NOT NULL,
  REVOCATION_TIMESTAMP TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (REVOKED_BY, REQUEST_RESOURCE_ID,INSTRUCTION_END_TO_END_ID),
  CONSTRAINT FK_REVOCATION_HISTORY FOREIGN KEY
  (REQUEST_RESOURCE_ID) REFERENCES STET_PAYMENT_CONSENT (REQUEST_RESOURCE_ID)
    ON DELETE CASCADE
)
 /

CREATE TABLE STET_ACCOUNT_CONSENT (
    PSU_ID                  VARCHAR(255)    NOT NULL,
    TPP_UNIQUE_ID           VARCHAR(255)    NOT NULL,
    ACCOUNT_CONSENT         CLOB            NOT NULL,
    PRIMARY KEY (PSU_ID, TPP_UNIQUE_ID)
)
 /

