-- Migrate from 1.0.0 to 1.1.0-M2
ALTER TABLE UK_ACCOUNT_INITIATION ADD REVOCATION_USER VARCHAR(255) DEFAULT NULL AFTER CLIENT_ID;
ALTER TABLE UK_ACCOUNT_INITIATION ADD REVOCATION_REASON VARCHAR(MAX) DEFAULT NULL AFTER REVOCATION_USER;

-- Migrate from 1.1.0-M2 to 1.1.0-M3
ALTER TABLE UK_ACCOUNT_INITIATION ALTER COLUMN TIMESTAMP RENAME TO CREATED_TIMESTAMP;
ALTER TABLE UK_ACCOUNT_INITIATION ADD STATUS_UPDATED_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_DATE() AFTER REVOCATION_REASON;

ALTER TABLE UK_ACCOUNT_INITIATION DROP COLUMN REVOCATION_REASON;
ALTER TABLE UK_ACCOUNT_INITIATION DROP COLUMN REVOCATION_USER;

CREATE TABLE IF NOT EXISTS UK_ACCOUNT_CONSENT_REVOCATION_HISTORY (
  CONSENT_ID VARCHAR(255) NOT NULL,
  REVOCATION_USER VARCHAR(255) NOT NULL,
  REVOCATION_REASON VARCHAR(60000) NOT NULL,
  PRIMARY KEY (CONSENT_ID),
    CONSTRAINT FK_CONSENT_ID_UK_ACCOUNT_CONSENT_REVOCATION_HISTORY FOREIGN KEY (CONSENT_ID)  REFERENCES UK_ACCOUNT_INITIATION (ID)
    ON DELETE CASCADE
);
