ALTER TABLE OB_DCR_DETAILS ADD APPLICATION_ID NUMBER(10) NOT NULL;
ALTER TABLE OB_DCR_DETAILS ADD SOFTWARE_ID VARCHAR2(255) NOT NULL;
ALTER TABLE OB_DCR_DETAILS ADD CLID_ISSUED_AT NUMBER(10) NOT NULL;