CREATE TABLE  IF NOT EXISTS OB_DCR_DETAILS (
  ID VARCHAR(255) NOT NULL,
  TPP_NAME VARCHAR(255) NOT NULL,
  REQUEST_HEADER JSON NOT NULL,
  REQUEST JSON NOT NULL,
  CLIENT_ID VARCHAR(255) NOT NULL,
  SOFTWARE_ENV VARCHAR(255) NOT NULL,
  APPLICATION_ID INT NOT NULL,
  SOFTWARE_ID VARCHAR(255) NOT NULL,
  SPEC_VERSION VARCHAR(64) NOT NULL,
  CREATED_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  STATUS VARCHAR(64) NOT NULL,
  CLID_ISSUED_AT INT NOT NULL,
  STATUS_UPDATED_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
)ENGINE INNODB;
