sp_rename BG_PAYMENT_CONSENT_REVOCATION_HISTORY, BG_PAYMENT_CONSENT_REVOCATION;
sp_rename BG_ACCOUNT_CONSENT_STATUS_HISTORY, BG_ACCOUNT_CONSENT_STATUS;
sp_rename BG_PAYMENT_CONSENT_USER_MAPPING, BG_PAYMENT_CONSENT_MAPPING;
sp_rename FK_PAYMENT_ID_BG_PAYMENT_CONSENT_USER_MAPPING, FK_PAYMENT_ID_BG_PAYMENT_CONSENT_MAPPING; 
sp_rename FK_PAYMENT_ID_BG_PAYMENT_CONSENT_REVOCATION_HISTORY, FK_PAYMENT_ID_BG_PAYMENT_CONSENT_REVOCATION; 
sp_rename FK_CONSENT_ID_BG_ACCOUNT_CONSENT_STATUS_HISTORY, FK_CONSENT_ID_BG_ACCOUNT_CONSENT_STATUS; 

CREATE TABLE BG_ACCOUNT_CONSENT_FREQUENCY (
   USER_ID VARCHAR(255),
   TPP_UNIQUE_ID VARCHAR(255) NOT NULL,
   CONSENT_ID VARCHAR(255)  NOT NULL,
   FREQUENCY_PER_DAY INT NOT NULL,
   ID INT IDENTITY(1,1),
   PRIMARY KEY (ID)
);
