ALTER TABLE BG_PAYMENT_CONSENT_USER_MAPPING  RENAME TO BG_PAYMENT_CONSENT_MAPPING;
ALTER TABLE BG_PAYMENT_CONSENT_REVOCATION_HISTORY  RENAME TO BG_PAYMENT_CONSENT_REVOCATION;
ALTER TABLE BG_ACCOUNT_CONSENT_STATUS_HISTORY  RENAME TO BG_ACCOUNT_CONSENT_STATUS;


ALTER TABLE BG_PAYMENT_CONSENT_MAPPING
  DROP FOREIGN KEY FK_PAYMENT_ID_BG_PAYMENT_CONSENT_USER_MAPPING,
  ADD  CONSTRAINT FK_PAYMENT_ID_BG_PAYMENT_CONSENT_MAPPING 
	FOREIGN KEY (PAYMENT_ID) REFERENCES BG_PAYMENT_CONSENT (PAYMENT_ID);


ALTER TABLE BG_PAYMENT_CONSENT_REVOCATION
  DROP FOREIGN KEY FK_PAYMENT_ID_BG_PAYMENT_CONSENT_REVOCATION_HISTORY,
  ADD  CONSTRAINT FK_PAYMENT_ID_BG_PAYMENT_CONSENT_REVOCATION 
	FOREIGN KEY (PAYMENT_ID) REFERENCES BG_PAYMENT_CONSENT (PAYMENT_ID);

ALTER TABLE BG_ACCOUNT_CONSENT_STATUS
  DROP FOREIGN KEY FK_CONSENT_ID_BG_ACCOUNT_CONSENT_STATUS_HISTORY,
  ADD  CONSTRAINT FK_CONSENT_ID_BG_ACCOUNT_CONSENT_STATUS 
	FOREIGN KEY (CONSENT_ID) REFERENCES BG_ACCOUNT_INITIALIZATION (CONSENT_ID);

CREATE TABLE BG_ACCOUNT_CONSENT_FREQUENCY (
   USER_ID VARCHAR(255),
   TPP_UNIQUE_ID VARCHAR(255) NOT NULL,
   CONSENT_ID VARCHAR(255)  NOT NULL,
   FREQUENCY_PER_DAY INT NOT NULL,
   ID INT NOT NULL AUTO_INCREMENT,
   PRIMARY KEY (ID)
) ENGINE INNODB;
