CREATE TABLE IF NOT EXISTS UK_TRANSACTION_INITIATION (
  ID        VARCHAR(255)  NOT NULL,
  REQUEST   NVARCHAR(MAX) NOT NULL,
  TIMESTAMP DATETIME      NOT NULL DEFAULT CURRENT_DATE(),
  STATUS    VARCHAR(64)   NOT NULL DEFAULT 0,
  CLIENT_ID VARCHAR(255)  NOT NULL,
  IDEMPOTENT_KEY VARCHAR(64) NOT NULL ,
  STATUS_UPDATED_TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  SPEC_VERSION VARCHAR(64)   NOT NULL,
  PRIMARY KEY (ID),
);

CREATE TABLE IF NOT EXISTS UK_ACCOUNT_INITIATION (
  ID        VARCHAR(255)  NOT NULL,
  REQUEST   NVARCHAR(MAX) NOT NULL ,
  CREATED_TIMESTAMP DATETIME      NOT NULL DEFAULT CURRENT_DATE(),
  STATUS    VARCHAR(64)   NOT NULL DEFAULT 0,
  CLIENT_ID VARCHAR(255)  NOT NULL,
  STATUS_UPDATED_TIMESTAMP DATETIME      NOT NULL DEFAULT CURRENT_DATE(),
  SPEC_VERSION VARCHAR(64)   NOT NULL,
  PRIMARY KEY (ID),
);


CREATE TABLE IF NOT EXISTS UK_COF_INITIATION (
  ID        VARCHAR(255)  NOT NULL,
  REQUEST   NVARCHAR(MAX) NOT NULL ,
  CREATED_TIMESTAMP DATETIME      NOT NULL DEFAULT CURRENT_DATE(),
  STATUS    VARCHAR(64)   NOT NULL DEFAULT 0,
  CLIENT_ID VARCHAR(255)  NOT NULL,
  STATUS_UPDATED_TIMESTAMP DATETIME      NOT NULL DEFAULT CURRENT_DATE(),
  SPEC_VERSION VARCHAR(64)   NOT NULL,
  PRIMARY KEY (ID),
);

CREATE TABLE IF NOT EXISTS UK_TRANSACTION_CONSENT_BINDING (
  USER_ID           VARCHAR(255) NOT NULL,
  CONSENT_ID        VARCHAR(255) NOT NULL,
  DEBTOR_ACCOUNT    VARCHAR(255) NOT NULL,
  TIMESTAMP         DATETIME     NOT NULL DEFAULT CURRENT_DATE(),
  COLLECTION_METHOD VARCHAR(64),
  PRIMARY KEY (USER_ID, CONSENT_ID),
  CONSTRAINT UK_CONSENT_ID_FK FOREIGN KEY (CONSENT_ID) REFERENCES UK_TRANSACTION_INITIATION (ID)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS UK_ACCOUNT_CONSENT_BINDING (
  USER_ID           VARCHAR(255) NOT NULL,
  CONSENT_ID        VARCHAR(255) NOT NULL,
  ACCOUNT_ID        VARCHAR(255) NOT NULL,
  TIMESTAMP         DATETIME     NOT NULL DEFAULT CURRENT_DATE(),
  COLLECTION_METHOD VARCHAR(64),
  PRIMARY KEY (USER_ID, CONSENT_ID,ACCOUNT_ID),
  CONSTRAINT FK_CONSENT_ID_UK_ACCOUNT_CONSENT_BINDING FOREIGN KEY (CONSENT_ID) REFERENCES UK_ACCOUNT_INITIATION (ID)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS UK_COF_CONSENT_BINDING (
  USER_ID           VARCHAR(255) NOT NULL,
  CONSENT_ID        VARCHAR(255) NOT NULL,
  ACCOUNT_ID        VARCHAR(255) NOT NULL,
  TIMESTAMP         DATETIME     NOT NULL DEFAULT CURRENT_DATE(),
  COLLECTION_METHOD VARCHAR(64),
  PRIMARY KEY (USER_ID, CONSENT_ID,ACCOUNT_ID),
  CONSTRAINT FK_CONSENT_ID_UK_COF_CONSENT_BINDING FOREIGN KEY (CONSENT_ID) REFERENCES UK_COF_INITIATION (ID)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS UK_ACCOUNT_CONSENT_REV_HISTORY (
  CONSENT_ID VARCHAR(255) NOT NULL,
  REVOCATION_USER VARCHAR(255) NOT NULL,
  REVOCATION_REASON VARCHAR(2048) NOT NULL,
  PRIMARY KEY (CONSENT_ID),
  CONSTRAINT FK_CONSENT_ID_UK_ACCOUNT_CONSENT_REVOCATION_HISTORY FOREIGN KEY (CONSENT_ID)  REFERENCES UK_ACCOUNT_INITIATION (ID)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS UK_COF_CONSENT_REV_HISTORY (
  CONSENT_ID VARCHAR(255) NOT NULL,
  REVOCATION_USER VARCHAR(255) NOT NULL,
  REVOCATION_REASON VARCHAR(2048) NOT NULL,
  PRIMARY KEY (CONSENT_ID),
  CONSTRAINT FK_CONSENT_ID_UK_FUNDS_CONFIRMATION_CONSENT_REVOCATION_HISTORY FOREIGN KEY (CONSENT_ID)  REFERENCES UK_COF_INITIATION (ID)
    ON DELETE CASCADE
);
