CREATE TABLE UK_NOTIFICATION_CALLBACK (
  ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  CLIENT_ID varchar(50) NOT NULL,
  REQUEST varchar(1000) NOT NULL CHECK ( ISJSON(REQUEST) > 0 ),
  SPEC_VERSION varchar(10) NOT NULL,
  TIMESTAMP DATETIME NOT NULL DEFAULT getdate()
);

CREATE TABLE UK_NOTIFICATION (
  ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  RESOURCE_ID varchar(50) NOT NULL,
  RESOURCE_TYPE varchar(50) NOT NULL,
  RESOURCE_LINK varchar(200) NOT NULL,
  VERSION varchar(10) NOT NULL,
  CLIENT_ID varchar(50) NOT NULL,
  STATUS varchar(10) NOT NULL,
  TIMESTAMP DATETIME NOT NULL,
  LAST_RETRY_TIME DATETIME NOT NULL,
  NEXT_RETRY_TIME DATETIME  NOT NULL
  );
