CREATE SEQUENCE callback_seq START WITH 1;
/
CREATE TABLE UK_NOTIFICATION_CALLBACK (
  ID NUMBER(10) DEFAULT callback_seq.nextval NOT NULL,
  CLIENT_ID VARCHAR2(50) NOT NULL,
  REQUEST CLOB NOT NULL,
  TIMESTAMP timestamp NULL,
  SPEC_VERSION VARCHAR2(10) NOT NULL,
  CONSTRAINT callback_pk PRIMARY KEY (ID),
  CONSTRAINT ENSURE_JSON_REQUEST_CALLBACK CHECK (REQUEST IS JSON)
);
/
CREATE SEQUENCE notif_seq START WITH 1;
/
CREATE TABLE UK_NOTIFICATION (
  ID NUMBER(10) DEFAULT notif_seq.nextval NOT NULL,
  RESOURCE_ID VARCHAR2(50) NOT NULL,
  RESOURCE_TYPE VARCHAR2(50) NOT NULL,
  RESOURCE_LINK VARCHAR2(200) NOT NULL,
  VERSION VARCHAR2(10) NOT NULL,
  CLIENT_ID VARCHAR2(50) NOT NULL,
  STATUS VARCHAR2(10) NOT NULL,
  TIMESTAMP timestamp NULL,
  LAST_RETRY_TIME timestamp NULL,
  NEXT_RETRY_TIME timestamp NULL,
  TRY_COUNT NUMBER(10) NOT NULL,
  CONSTRAINT notif_pk PRIMARY KEY (ID)
);
