BEGIN TRANSACTION;

INSERT INTO UK_CONSENT_REV SELECT b.* FROM UK_ACCOUNT_CONSENT_BINDING AS b INNER JOIN UK_ACCOUNT_INITIATION AS i ON b.CONSENT_ID = i.ID AND i.STATUS='Revoked';

DELETE FROM UK_ACCOUNT_CONSENT_BINDING WHERE CONSENT_ID IN (SELECT CONSENT_ID FROM (SELECT b.CONSENT_ID FROM UK_ACCOUNT_CONSENT_BINDING AS b INNER JOIN UK_ACCOUNT_INITIATION AS i ON b.CONSENT_ID = i.ID AND i.STATUS='Revoked') AS c);

COMMIT;

BEGIN TRANSACTION;

UPDATE UK_TRANSACTION_INITIATION SET STATUS_UPDATED_TIMESTAMP = TIMESTAMP;

COMMIT;

BEGIN TRANSACTION;

INSERT INTO OB_CONSENT_METADATA SELECT ID AS CONSENT_ID, 'PISP' AS CONSENT_TYPE, 'PaymentType' AS METADATA_KEY, JSON_VALUE(REQUEST,'$.paymentType') AS METADATA_VALUE FROM UK_TRANSACTION_INITIATION;

COMMIT;

ALTER TABLE UK_NOTIFICATION_CALLBACK DROP COLUMN URL;
ALTER TABLE UK_NOTIFICATION_CALLBACK DROP COLUMN VERSION;