INSERT INTO UK_CONSENT_REV (SELECT UK_ACCOUNT_CONSENT_BINDING.* FROM UK_ACCOUNT_CONSENT_BINDING INNER JOIN UK_ACCOUNT_INITIATION ON UK_ACCOUNT_CONSENT_BINDING.CONSENT_ID = UK_ACCOUNT_INITIATION.ID AND UK_ACCOUNT_INITIATION.STATUS='Revoked');

DELETE FROM UK_ACCOUNT_CONSENT_BINDING WHERE CONSENT_ID IN (SELECT CONSENT_ID FROM UK_ACCOUNT_CONSENT_BINDING INNER JOIN UK_ACCOUNT_INITIATION ON UK_ACCOUNT_CONSENT_BINDING.CONSENT_ID = UK_ACCOUNT_INITIATION.ID AND UK_ACCOUNT_INITIATION.STATUS='Revoked');

COMMIT;

UPDATE UK_TRANSACTION_INITIATION SET STATUS_UPDATED_TIMESTAMP = TIMESTAMP;

COMMIT;

INSERT INTO OB_CONSENT_METADATA (SELECT ID AS CONSENT_ID, 'PISP' AS CONSENT_TYPE, 'PaymentType' AS METADATA_KEY, JSON_VALUE(REQUEST,'$.paymentType') AS METADATA_VALUE FROM UK_TRANSACTION_INITIATION);

COMMIT;

alter table UK_NOTIFICATION_CALLBACK drop column URL;
alter table UK_NOTIFICATION_CALLBACK drop column VERSION;

