CREATE TABLE IF NOT EXISTS BG_PAYMENT_CONSENT (
  PAYMENT_ID                   VARCHAR(255)  NOT NULL,
  REQUEST_BODY                 NVARCHAR(MAX) NOT NULL,
  PAYMENT_TYPE                 VARCHAR(255)  NOT NULL,
  PAYMENT_PRODUCT              VARCHAR(255)  NOT NULL,
  REQUEST_INITIATION_TIMESTAMP DATETIME      NOT NULL DEFAULT CURRENT_DATE(),
  TRANSACTION_STATUS           VARCHAR(64)   NOT NULL DEFAULT 0,
  TPP_UNIQUE_ID                VARCHAR(255)  NOT NULL,
  X_REQUEST_ID                 VARCHAR(255)   NOT NULL,
  PSU_ID                       VARCHAR(255),
  PSU_ID_TYPE                  VARCHAR(255),
  PSU_CORPORATE_ID             VARCHAR(255),
  PSU_CORPORATE_ID_TYPE        VARCHAR(255),
  PRIMARY KEY (PAYMENT_ID)
);

CREATE TABLE IF NOT EXISTS BG_PAYMENT_CONSENT_MAPPING (
  USER_ID           VARCHAR(255) NOT NULL,
  PAYMENT_ID        VARCHAR(255) NOT NULL,
  UPDATED_TIMESTAMP DATETIME     NOT NULL DEFAULT CURRENT_DATE(),
  PRIMARY KEY (USER_ID, PAYMENT_ID),
  CONSTRAINT FK_PAYMENT_ID_BG_PAYMENT_CONSENT_MAPPING FOREIGN KEY (PAYMENT_ID) REFERENCES BG_PAYMENT_CONSENT (PAYMENT_ID)
  ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS BG_PAYMENT_CONSENT_REVOCATION (
  REVOKED_BY           VARCHAR(255)  NOT NULL,
  PAYMENT_ID           VARCHAR(255)  NOT NULL,
  REASON               VARCHAR(1000) NOT NULL,
  REVOCATION_TIMESTAMP DATETIME      NOT NULL DEFAULT CURRENT_DATE(),
  PRIMARY KEY (REVOKED_BY, PAYMENT_ID),
  CONSTRAINT FK_PAYMENT_ID_BG_PAYMENT_CONSENT_REVOCATION FOREIGN KEY (PAYMENT_ID) REFERENCES BG_PAYMENT_CONSENT (PAYMENT_ID)
  ON DELETE CASCADE
);

-- TODO: Untested on running system.
-- ACCOUNT ACCESS BINDING
-- FOR BANK OFFERED CONSENT & QUERYING
CREATE TABLE BG_ACCOUNT_ACCESS_BINDING (
  CONSENT_ID VARCHAR(255)  NOT NULL,
  ACCOUNTS VARCHAR(15000),
  BALANCES VARCHAR(15000),
  TRANSACTIONS VARCHAR(15000),
  PRIMARY KEY (CONSENT_ID),
  CONSTRAINT FK_CONSENT_ID_BG_ACCOUNT_ACCESS_BINDING FOREIGN KEY (CONSENT_ID) REFERENCES BG_ACCOUNT_INITIALIZATION (CONSENT_ID)
    ON DELETE CASCADE
);

-- TODO: Untested on running system.
-- AUTHORISATION SUB RESOURCE TABLE
-- BINDS CONSENT TO AUTHORISATION RESOURCE
CREATE TABLE BG_AUTH_RESOURCE (
  -- PRIMARY KEY
  X_REQUEST_ID        VARCHAR(255)  NOT NULL,
  AUTH_TYPE           VARCHAR(255)  NOT NULL,
  CONSENT_ID          VARCHAR(255)  NOT NULL,
  CONSENT_TYPE        VARCHAR(255)  NOT NULL,
  AUTH_ID             VARCHAR(255)  NOT NULL,
  -- USER BINDING
  USER_ID             VARCHAR(255),
  AUTH_STATUS         VARCHAR(255)  NOT NULL,
  -- METADATA
  UPDATED_TIMESTAMP   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  API_VERSION         VARCHAR(255)  NOT NULL,
  -- COMPOSITE CONSTRAINT
  PRIMARY KEY (X_REQUEST_ID, AUTH_TYPE, CONSENT_ID, CONSENT_TYPE, AUTH_ID)
);
