CREATE TABLE IF NOT EXISTS BG_PAYMENT_CONSENT (
  PAYMENT_ID                   CHARACTER VARYING(255)      NOT NULL,
  REQUEST_BODY                 CHARACTER VARYING(60000)    NOT NULL,
  PAYMENT_TYPE                 CHARACTER VARYING(255)      NOT NULL,
  PAYMENT_PRODUCT              CHARACTER VARYING(255)      NOT NULL,
  REQUEST_INITIATION_TIMESTAMP TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
  TRANSACTION_STATUS           CHARACTER VARYING(64)       NOT NULL DEFAULT 0,
  TPP_UNIQUE_ID                CHARACTER VARYING(255)      NOT NULL,
  X_REQUEST_ID                 CHARACTER VARYING(255)      NOT NULL,
  PSU_ID                       CHARACTER VARYING(255),
  PSU_ID_TYPE                  CHARACTER VARYING(255),
  PSU_CORPORATE_ID             CHARACTER VARYING(255),
  PSU_CORPORATE_ID_TYPE        CHARACTER VARYING(255),
  CONSTRAINT BG_PAYMENT_CONSENT_PKEY PRIMARY KEY (PAYMENT_ID)
);

CREATE TABLE IF NOT EXISTS BG_PAYMENT_CONSENT_MAPPING (
  USER_ID           CHARACTER VARYING(255)      NOT NULL,
  PAYMENT_ID        CHARACTER VARYING(255)      NOT NULL,
  UPDATED_TIMESTAMP TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
  PRIMARY KEY (USER_ID, PAYMENT_ID),
  FOREIGN KEY (PAYMENT_ID) REFERENCES BG_PAYMENT_CONSENT (PAYMENT_ID)
  ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS BG_PAYMENT_CONSENT_REVOCATION (
  REVOKED_BY           CHARACTER VARYING(255)      NOT NULL,
  PAYMENT_ID           CHARACTER VARYING(255)      NOT NULL,
  REASON               CHARACTER VARYING(1000)     NOT NULL,
  REVOCATION_TIMESTAMP TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
  PRIMARY KEY (REVOKED_BY, PAYMENT_ID),
  FOREIGN KEY (PAYMENT_ID) REFERENCES BG_PAYMENT_CONSENT (PAYMENT_ID)
  ON DELETE CASCADE
);
